"use client";

import React from 'react';
import { Card } from './ui/card';

interface LineItem {
    id: string;
    description: string;
    quantity: number;
    unitPrice: number;
}

interface InvoiceData {
    businessName: string;
    businessAddress: string;
    businessTIN: string;
    clientName: string;
    clientAddress: string;
    items: LineItem[];
    vatRate: number;
}

export default function InvoicePreview({ data }: { data: InvoiceData }) {
    const subtotal = data.items.reduce((sum, item) => sum + (item.quantity * item.unitPrice), 0);
    const vatAmount = (subtotal * data.vatRate) / 100;
    const total = subtotal + vatAmount;

    return (
        <Card className="p-8 bg-white text-black min-h-[800px] flex flex-col shadow-lg">
            <div className="flex justify-between items-start mb-12">
                <div>
                    <h1 className="text-3xl font-bold uppercase tracking-wider mb-2">Invoice</h1>
                    <p className="text-gray-500">#{new Date().getFullYear()}-{Math.floor(1000 + Math.random() * 9000)}</p>
                </div>
                <div className="text-right">
                    <h2 className="text-xl font-bold">{data.businessName || 'Your Company'}</h2>
                    <p className="text-gray-600 max-w-xs">{data.businessAddress || 'Address'}</p>
                    {data.businessTIN && <p className="text-gray-600">TIN: {data.businessTIN}</p>}
                </div>
            </div>

            <div className="mb-12">
                <h3 className="text-sm font-bold uppercase text-gray-500 mb-2">Bill To:</h3>
                <p className="text-lg font-bold">{data.clientName || 'Client Name'}</p>
                <p className="text-gray-600 max-w-xs">{data.clientAddress || 'Client Address'}</p>
            </div>

            <div className="flex-grow">
                <table className="w-full text-left">
                    <thead>
                        <tr className="border-b-2 border-black">
                            <th className="py-2 font-bold uppercase text-sm">Description</th>
                            <th className="py-2 text-right font-bold uppercase text-sm">Qty</th>
                            <th className="py-2 text-right font-bold uppercase text-sm">Unit Price</th>
                            <th className="py-2 text-right font-bold uppercase text-sm">Amount</th>
                        </tr>
                    </thead>
                    <tbody>
                        {data.items.map((item) => (
                            <tr key={item.id} className="border-b">
                                <td className="py-4">{item.description || 'Item description'}</td>
                                <td className="py-4 text-right">{item.quantity}</td>
                                <td className="py-4 text-right">{item.unitPrice.toLocaleString()} ETB</td>
                                <td className="py-4 text-right font-semibold">{(item.quantity * item.unitPrice).toLocaleString()} ETB</td>
                            </tr>
                        ))}
                    </tbody>
                </table>
            </div>

            <div className="mt-12 flex justify-end">
                <div className="w-64 space-y-2">
                    <div className="flex justify-between py-2 border-b">
                        <span className="text-gray-600">Subtotal</span>
                        <span>{subtotal.toLocaleString()} ETB</span>
                    </div>
                    <div className="flex justify-between py-2 border-b">
                        <span className="text-gray-600">VAT ({data.vatRate}%)</span>
                        <span>{vatAmount.toLocaleString()} ETB</span>
                    </div>
                    <div className="flex justify-between py-2 text-xl font-bold">
                        <span>Total</span>
                        <span className="text-primary">{total.toLocaleString()} ETB</span>
                    </div>
                </div>
            </div>

            <div className="mt-20 pt-8 border-t text-center text-gray-400 text-sm">
                <p>Thank you for your business!</p>
                <p>Generated by Freelancer Invoice Tool</p>
            </div>
        </Card>
    );
}
