"use client";

import React from 'react';
import { Button } from '@/components/ui/button';
import { ArrowLeft, Scale, ShieldAlert, BadgeCheck, FileText } from 'lucide-react';
import Link from 'next/link';

export default function TermsOfService() {
    return (
        <div className="min-h-screen bg-white font-outfit">
            <nav className="border-b bg-white/80 backdrop-blur-md sticky top-0 z-50">
                <div className="max-w-4xl mx-auto px-4 h-16 flex items-center justify-between">
                    <Link href="/" className="flex items-center gap-2 text-sm font-bold text-gray-500 hover:text-primary transition-colors">
                        <ArrowLeft className="w-4 h-4" />
                        Back to Home
                    </Link>
                    <div className="flex items-center gap-2">
                        <div className="bg-primary/10 p-1.5 rounded-lg">
                            <Scale className="text-primary w-4 h-4" />
                        </div>
                        <span className="text-sm font-bold text-gray-900">Legal Terms</span>
                    </div>
                </div>
            </nav>

            <main className="max-w-4xl mx-auto px-4 py-20">
                <div className="space-y-12">
                    <header className="space-y-4">
                        <div className="inline-flex items-center gap-2 px-3 py-1 rounded-full bg-blue-50 text-blue-600 text-[10px] font-bold uppercase tracking-widest">
                            Legal Disclaimer
                        </div>
                        <h1 className="text-4xl sm:text-6xl font-black text-gray-900 leading-tight">Terms of Service</h1>
                        <p className="text-xl text-gray-500 leading-relaxed font-medium">
                            Please read these terms carefully before using the Service.
                        </p>
                    </header>

                    <div className="grid grid-cols-1 md:grid-cols-3 gap-8 py-10 border-y border-gray-100">
                        <div className="space-y-4">
                            <div className="w-12 h-12 bg-amber-50 text-amber-600 rounded-2xl flex items-center justify-center">
                                <ShieldAlert className="w-6 h-6" />
                            </div>
                            <h3 className="font-bold text-gray-900 text-lg">No Liability</h3>
                            <p className="text-sm text-gray-500 leading-relaxed">We are not liable for tax errors or legal disputes arising from generated invoices.</p>
                        </div>
                        <div className="space-y-4">
                            <div className="w-12 h-12 bg-blue-50 text-blue-600 rounded-2xl flex items-center justify-center">
                                <BadgeCheck className="w-6 h-6" />
                            </div>
                            <h3 className="font-bold text-gray-900 text-lg">Proper Usage</h3>
                            <p className="text-sm text-gray-500 leading-relaxed">Users are responsible for ensuring their invoices comply with local tax laws.</p>
                        </div>
                        <div className="space-y-4">
                            <div className="w-12 h-12 bg-green-50 text-green-600 rounded-2xl flex items-center justify-center">
                                <FileText className="w-6 h-6" />
                            </div>
                            <h3 className="font-bold text-gray-900 text-lg">Content Ownership</h3>
                            <p className="text-sm text-gray-500 leading-relaxed">You own the rights to all data entered and invoices generated by you.</p>
                        </div>
                    </div>

                    <article className="prose prose-blue prose-lg max-w-none 
                        prose-headings:font-black prose-headings:text-gray-900 
                        prose-p:text-gray-600 prose-p:leading-relaxed 
                        prose-strong:text-gray-900 prose-strong:font-bold
                    ">
                        <h2>1. Agreement to Terms</h2>
                        <p>By accessing or using InvoiceGen, you agree to be bound by these Terms of Service. If you disagree with any part of these terms, you may not access the service.</p>

                        <h2>2. Description of Service</h2>
                        <p>InvoiceGen provides a web-based platform for creating, sharing, and managing professional invoices. We offer both free and premium subscription-based features.</p>

                        <h2>3. User Responsibilities</h2>
                        <p>As a user, you are responsible for:</p>
                        <ul>
                            <li>The accuracy of all information entered into your invoices.</li>
                            <li>Compliance with local tax regulations and accounting standards.</li>
                            <li>Maintaining the security of your account credentials.</li>
                            <li>Ensuring that you have the right to bill the clients you list.</li>
                        </ul>

                        <h2>4. Limitation of Liability</h2>
                        <p>InvoiceGen is provided "as is" and "as available". We do not warrant that the service will be uninterrupted or error-free. In no event shall InvoiceGen, its founders, or employees be liable for any financial losses, tax penalties, or legal disputes resulting from the use of our generated documents.</p>

                        <h2>5. Payments and Subscriptions</h2>
                        <p>Subscription fees for premium tiers are billed in advance. All payments are non-refundable unless required by law. You may cancel your subscription at any time.</p>

                        <h2>6. Termination</h2>
                        <p>We reserve the right to terminate or suspend your account immediately, without prior notice or liability, for any reason whatsoever, including without limitation if you breach the Terms.</p>

                        <h2>7. Changes to Terms</h2>
                        <p>We reserve the right to modify or replace these Terms at any time. We will provide at least 30 days' notice prior to any new terms taking effect for significant changes.</p>

                        <h2>8. Contact Legal</h2>
                        <p>For legal inquiries, please reach out to <strong>hermelagetachew999@gmail.com</strong></p>
                    </article>
                </div>
            </main>

            <footer className="bg-gray-900 text-white py-20">
                <div className="max-w-4xl mx-auto px-4 text-center space-y-6">
                    <div className="text-2xl font-black">InvoiceGen</div>
                    <p className="text-gray-400 max-w-md mx-auto">Standard legal terms for a safe and professional experience.</p>
                    <div className="pt-10 border-t border-white/10 text-[10px] text-gray-500 font-bold uppercase tracking-wider">
                        &copy; 2026 InvoiceGen. All rights reserved.
                    </div>
                </div>
            </footer>
        </div>
    );
}
