import { jsPDF } from "jspdf";

interface LineItem {
    id: string;
    description: string;
    quantity: number;
    unitPrice: number;
}

interface InvoiceData {
    businessName: string;
    businessAddress: string;
    businessTIN: string;
    clientName: string;
    clientAddress: string;
    items: LineItem[];
    vatRate: number;
}

export const generatePDF = (data: InvoiceData) => {
    const doc = new jsPDF();
    const pageWidth = doc.internal.pageSize.getWidth();
    const margin = 20;

    // Header
    doc.setFontSize(24);
    doc.setTextColor(59, 130, 246); // Primary Color
    doc.text("INVOICE", margin, 30);

    doc.setFontSize(10);
    doc.setTextColor(100, 116, 139);
    doc.text(`#${new Date().getFullYear()}-${Math.floor(1000 + Math.random() * 9000)}`, margin, 38);

    // Business Info
    doc.setFontSize(12);
    doc.setTextColor(0);
    doc.setFont("helvetica", "bold");
    doc.text(data.businessName || "Your Company", pageWidth - margin, 30, { align: "right" });

    doc.setFont("helvetica", "normal");
    doc.setFontSize(10);
    doc.setTextColor(100);
    const businessAddressLines = doc.splitTextToSize(data.businessAddress || "Your Address", 60);
    doc.text(businessAddressLines, pageWidth - margin, 36, { align: "right" });

    if (data.businessTIN) {
        doc.text(`TIN: ${data.businessTIN}`, pageWidth - margin, 36 + (businessAddressLines.length * 5), { align: "right" });
    }

    // Client Info
    doc.setFontSize(10);
    doc.setTextColor(150);
    doc.text("BILL TO:", margin, 60);

    doc.setFontSize(12);
    doc.setTextColor(0);
    doc.setFont("helvetica", "bold");
    doc.text(data.clientName || "Client Name", margin, 66);

    doc.setFont("helvetica", "normal");
    doc.setFontSize(10);
    doc.setTextColor(100);
    const clientAddressLines = doc.splitTextToSize(data.clientAddress || "Client Address", 60);
    doc.text(clientAddressLines, margin, 72);

    // Table Header
    const tableTop = 100;
    doc.setDrawColor(0);
    doc.setLineWidth(0.5);
    doc.line(margin, tableTop, pageWidth - margin, tableTop);

    doc.setFont("helvetica", "bold");
    doc.setTextColor(0);
    doc.text("Description", margin, tableTop + 7);
    doc.text("Qty", pageWidth - 70, tableTop + 7, { align: "right" });
    doc.text("Unit Price", pageWidth - 45, tableTop + 7, { align: "right" });
    doc.text("Amount", pageWidth - margin, tableTop + 7, { align: "right" });

    doc.line(margin, tableTop + 12, pageWidth - margin, tableTop + 12);

    // Table Items
    doc.setFont("helvetica", "normal");
    let currentY = tableTop + 20;
    let subtotal = 0;

    data.items.forEach((item) => {
        const amount = item.quantity * item.unitPrice;
        subtotal += amount;

        const descLines = doc.splitTextToSize(item.description || "Service/Item", 80);
        doc.text(descLines, margin, currentY);
        doc.text(item.quantity.toString(), pageWidth - 70, currentY, { align: "right" });
        doc.text(`${item.unitPrice.toLocaleString()} ETB`, pageWidth - 45, currentY, { align: "right" });
        doc.text(`${amount.toLocaleString()} ETB`, pageWidth - margin, currentY, { align: "right" });

        currentY += Math.max(descLines.length * 5, 10);
    });

    // Totals
    const vatAmount = (subtotal * data.vatRate) / 100;
    const total = subtotal + vatAmount;

    currentY += 10;
    doc.line(pageWidth - 80, currentY, pageWidth - margin, currentY);

    currentY += 10;
    doc.text("Subtotal:", pageWidth - 80, currentY);
    doc.text(`${subtotal.toLocaleString()} ETB`, pageWidth - margin, currentY, { align: "right" });

    currentY += 7;
    doc.text(`VAT (${data.vatRate}%):`, pageWidth - 80, currentY);
    doc.text(`${vatAmount.toLocaleString()} ETB`, pageWidth - margin, currentY, { align: "right" });

    currentY += 10;
    doc.setFontSize(14);
    doc.setFont("helvetica", "bold");
    doc.setTextColor(59, 130, 246);
    doc.text("TOTAL:", pageWidth - 80, currentY);
    doc.text(`${total.toLocaleString()} ETB`, pageWidth - margin, currentY, { align: "right" });

    // Footer
    doc.setFontSize(10);
    doc.setTextColor(150);
    doc.setFont("helvetica", "normal");
    doc.text("Thank you for your business!", pageWidth / 2, 280, { align: "center" });
    doc.text("Generated by InvoiceGen.et", pageWidth / 2, 285, { align: "center" });

    doc.save(`Invoice_${data.clientName || 'Client'}.pdf`);
};
